version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.5GB"
